export const IMAGE_TYPE = {
  HOME_1: 'HOME_IMAGE_1',
  HOME_2: 'HOME_IMAGE_2',
  HOME_3: 'HOME_IMAGE_3',
  HOME_4: 'HOME_IMAGE_4',
  AVATAR: 'AVATAR',
  SERVICE: 'SERVICE_IMAGE',
  CONTACT_US: 'CONTACT_US_IMAGE',
};
