version: "3.7"
services:
  db:
    container_name: db
    build: ./.docker/postgres
    environment:
      POSTGRES_DB: rainbow_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdta:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3.6.6-management
    command: rabbitmq-server
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1
  cache:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./.docker/redis:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
volumes:
  pgdta:
    driver: local